apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
  - name: redis-container
    image: redis
    volumeMounts:
    - name: secretvol
      mountPath: /app-creds
      readOnly: true
  volumes:
  - name: secretvol
    secret:
      secretName: secret-creds
