apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-claim  
spec:        
  accessModes: 
  - ReadWriteOnce    
  storageClassName: host
  resources:
    requests:
      storage: 1Gi  
  selector:
    matchLabels:
      app: pvc      
            
            
      
